# Generated by Django 4.2.4 on 2023-08-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watt', models.IntegerField()),
                ('timestamp', models.TimeField()),
            ],
        ),
    ]
